import { H, B, C } from '@/constants/theme'
import { PageContainer, SectionLabel } from '@/components/common'

const benefits = [
  { title: 'Reach engaged learners', text: 'Introduce your programmes to students and families who are actively exploring their next education step.' },
  { title: 'Strengthen pathway guidance', text: 'Give learners clear, well-informed information about courses, entry requirements, and opportunities.' },
  { title: 'Build meaningful outcomes', text: 'Work with us to help young people make confident choices that lead to purposeful progress.' },
]

const partnershipTypes = ['Schools and career-guidance teams', 'Universities and colleges', 'Technical and vocational institutions', 'Employers and apprenticeship providers']

export function PartnersPage() {
  return <div className="w-full">
    <section className="site-section" style={{ backgroundColor: C.navy }}><PageContainer><div className="grid grid-cols-1 lg:grid-cols-[1.2fr_.8fr] gap-12 items-end"><div><SectionLabel>Institutional partnerships</SectionLabel><h1 className="text-white mb-6" style={{ fontFamily: H, fontWeight: 700, fontSize: 'clamp(38px, 5.5vw, 66px)', lineHeight: 1.04 }}>Help learners make their next step count.</h1><p className="text-base md:text-lg leading-relaxed max-w-2xl" style={{ color: 'rgba(255,255,255,.72)', fontFamily: B }}>Prospira-Edu partners with schools, colleges, universities, and employers to connect young people with relevant, well-informed opportunities.</p></div><div className="rounded-2xl p-7 md:p-8" style={{ border: '1px solid rgba(184,212,250,.3)', backgroundColor: 'rgba(255,255,255,.07)' }}><p className="text-xs uppercase tracking-[.16em] mb-4" style={{ color: '#B8D4FA', fontFamily: B }}>Built for shared impact</p><p className="text-white text-xl leading-snug" style={{ fontFamily: H, fontWeight: 700 }}>A stronger connection between aspiration, education, and opportunity.</p></div></div></PageContainer></section>
    <section className="py-14 md:py-20" style={{ backgroundColor: C.cream }}><PageContainer><div className="max-w-2xl mb-10"><SectionLabel>Why partner with us</SectionLabel><h2 style={{ fontFamily: H, color: C.navy, fontWeight: 700, fontSize: 'clamp(28px, 4vw, 46px)', lineHeight: 1.12 }}>Guidance that benefits your learners and your institution.</h2></div><div className="grid grid-cols-1 md:grid-cols-3 gap-5">{benefits.map(item => <article key={item.title} className="rounded-2xl p-7 md:p-8" style={{ backgroundColor: 'white', border: `1px solid ${C.border}` }}><h3 className="mb-3 text-xl" style={{ color: C.navy, fontFamily: H, fontWeight: 700 }}>{item.title}</h3><p className="text-sm leading-relaxed" style={{ color: C.bodyText, fontFamily: B }}>{item.text}</p></article>)}</div></PageContainer></section>
    <section className="py-14 md:py-20 bg-white"><PageContainer><div className="grid grid-cols-1 lg:grid-cols-2 gap-12"><div><SectionLabel>Who we work with</SectionLabel><h2 className="mb-5" style={{ fontFamily: H, color: C.navy, fontWeight: 700, fontSize: 'clamp(28px, 4vw, 44px)' }}>Partnerships designed around your role.</h2><p className="leading-relaxed" style={{ fontFamily: B, color: C.bodyText }}>Whether you are guiding a cohort of secondary-school learners or promoting a specialist programme, we create a clear route to collaboration.</p></div><div className="space-y-3">{partnershipTypes.map(type => <div key={type} className="p-5 rounded-xl" style={{ backgroundColor: C.blueLight, border: `1px solid ${C.border}` }}><span className="text-base font-semibold" style={{ fontFamily: H, color: C.navy }}>{type}</span></div>)}</div></div></PageContainer></section>
    <section className="py-14 md:py-20" style={{ backgroundColor: C.navyDark }}><PageContainer><div className="max-w-3xl mx-auto text-center"><SectionLabel>Start a conversation</SectionLabel><h2 className="text-white mb-5" style={{ fontFamily: H, fontWeight: 700, fontSize: 'clamp(30px, 4vw, 48px)' }}>Let us build a partnership with purpose.</h2><p className="mb-8 leading-relaxed" style={{ color: 'rgba(255,255,255,.67)', fontFamily: B }}>Tell us about your institution and the learners you want to reach. Our partnership team will be in touch.</p><a href="mailto:hello@prospira-edu.co.zw?subject=Partnership%20enquiry" className="inline-block px-7 py-3.5 rounded-lg text-sm font-semibold text-white no-underline" style={{ backgroundColor: C.blue, fontFamily: H }}>Contact the partnership team <span aria-hidden="true">&#8594;</span></a></div></PageContainer></section>
  </div>
}
