import { useState } from 'react'
import { H, B, C } from '@/constants/theme'
import { SectionLabel, PageContainer } from '@/components/common'

const steps = [
  { number: '01', title: 'Choose where and what to study', summary: 'We turn your goals, academic record, budget, and timeline into a realistic university shortlist.', points: ['Course and country matching', 'Entry requirements and English-test planning', 'Scholarship, bursary, and living-cost guidance'], action: 'Build my study plan' },
  { number: '02', title: 'Submit a strong university application', summary: 'Prepare each application with the documents and deadlines that matter to your chosen institutions.', points: ['Application timelines and document checklists', 'Personal statement and referee guidance', 'Offer comparison and decision support'], action: 'Plan my application' },
  { number: '03', title: 'Prepare to arrive with confidence', summary: 'Once you have an offer, we help you organise the practical details of moving overseas.', points: ['Student visa document and finance planning', 'Accommodation comparison and booking support', 'Pre-departure, arrival, and settling-in checklist'], action: 'Plan my move' },
]

const supportAreas = [
  { id: 'destinations', label: 'Study destinations', description: 'Compare the academic fit, costs, timelines, and student experience for your preferred regions.', names: ['United Kingdom & Ireland', 'Canada & United States', 'Australia & New Zealand', 'Europe & Asia'] },
  { id: 'visa', label: 'Visa and documentation', description: 'Know what needs to be prepared early so your visa application is complete and credible.', names: ['Passport and academic documents', 'English-language evidence', 'Financial evidence and sponsor documents', 'Country-specific visa checklist'] },
  { id: 'housing', label: 'Accommodation and arrival', description: 'Find a suitable place to live and avoid last-minute arrival stress.', names: ['University residence', 'Purpose-built student accommodation', 'Private shared housing', 'Airport arrival and move-in planning'] },
]

export function ServicesPage() {
  const [open, setOpen] = useState<string | null>('destinations')
  return <div className="w-full">
    <section className="py-16 md:py-22" style={{ backgroundColor: C.navy }}><PageContainer><div className="max-w-3xl"><SectionLabel>Study abroad support</SectionLabel><h1 className="text-white mb-5" style={{ fontFamily: H, fontWeight: 700, fontSize: 'clamp(36px, 5vw, 62px)', lineHeight: 1.06 }}>From university shortlist to a confident arrival.</h1><p className="text-base md:text-lg leading-relaxed max-w-2xl" style={{ fontFamily: B, color: 'rgba(255,255,255,0.7)' }}>Prospira-Edu helps students make informed choices about overseas universities, prepare visa applications, and secure accommodation that fits their needs.</p></div></PageContainer></section>
    <section className="py-14 md:py-20" style={{ backgroundColor: C.cream }}><PageContainer><div className="grid gap-5">{steps.map((step, index) => <article key={step.number} className="grid grid-cols-1 lg:grid-cols-[170px_1fr_260px] gap-6 lg:gap-10 rounded-2xl p-6 md:p-9" style={{ backgroundColor: 'white', border: `1px solid ${C.border}`, boxShadow: '0 10px 30px rgba(7,26,56,0.04)' }}><div><span className="text-sm font-semibold" style={{ color: C.blue, fontFamily: B }}>{step.number}</span><div className="h-px mt-4 w-14" style={{ backgroundColor: C.blue }} /></div><div><h2 className="mb-3" style={{ color: C.navy, fontFamily: H, fontWeight: 700, fontSize: 'clamp(22px, 3vw, 30px)' }}>{step.title}</h2><p className="leading-relaxed mb-5" style={{ color: C.bodyText, fontFamily: B }}>{step.summary}</p><ul className="space-y-3">{step.points.map(point => <li key={point} className="flex gap-3 text-sm leading-relaxed" style={{ color: C.bodyText, fontFamily: B }}><span style={{ color: C.blue }}>—</span>{point}</li>)}</ul></div><div className="flex lg:items-end"><a href="/portal" className="w-full rounded-lg px-5 py-3 text-sm font-semibold text-white text-center block no-underline" style={{ backgroundColor: index === 0 ? C.navy : C.blue, fontFamily: H }}>{step.action} <span aria-hidden="true">→</span></a></div></article>)}</div></PageContainer></section>
    <section className="py-14 md:py-20" style={{ backgroundColor: 'white' }}><PageContainer><div className="max-w-3xl mb-9"><SectionLabel>What we plan with you</SectionLabel><h2 style={{ fontFamily: H, color: C.navy, fontWeight: 700, fontSize: 'clamp(28px, 4vw, 44px)' }}>Every decision, in the right order.</h2></div><div className="max-w-4xl space-y-3">{supportAreas.map(area => <div key={area.id} className="rounded-xl overflow-hidden" style={{ border: `1px solid ${C.border}` }}><button onClick={() => setOpen(open === area.id ? null : area.id)} aria-expanded={open === area.id} className="w-full p-5 text-left flex items-center justify-between gap-6" style={{ backgroundColor: open === area.id ? C.blueLight : 'white' }}><span><span className="block text-base font-semibold mb-1" style={{ fontFamily: H, color: C.navy }}>{area.label}</span><span className="block text-sm" style={{ fontFamily: B, color: C.bodyText }}>{area.description}</span></span><span className="w-8 h-8 shrink-0 rounded-full flex items-center justify-center text-lg" style={{ color: C.navy, backgroundColor: 'white', border: `1px solid ${C.border}`, transform: open === area.id ? 'rotate(45deg)' : 'none', transition: 'transform .2s' }}>+</span></button>{open === area.id && <div className="p-5 pt-0 grid grid-cols-1 sm:grid-cols-2 gap-2" style={{ backgroundColor: C.blueLight }}>{area.names.map(name => <div key={name} className="rounded-lg px-4 py-3 text-sm" style={{ fontFamily: B, color: C.bodyText, backgroundColor: 'rgba(255,255,255,.72)' }}>{name}</div>)}</div>}</div>)}</div></PageContainer></section>
  </div>
}
